name: cpi-pr-validation

on: 
  pull_request:
    branches:
      - DEV

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate All iFlows In PR
        run: |

          echo "Checking all iFlows in PR..."

          files=$(find . -name "*.iflw")

          if [ -z "$files" ]; then
            echo "No iFlows found"
            exit 0
          fi

          for file in $files
          do

            filename=$(basename "$file" .iflw)

            if ! echo "$filename" | grep -E '^IFLOW_'; then
              echo "ERROR: Invalid iFlow -> $filename"
              echo "Expected naming convention: IFLOW_*"
              exit 1
            fi

          done

          echo "PR Validation Passed"
